name: Upload Firmware

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      wget_link:
        description: "Insert Wget Link"
        required: false
        default: ""
      gdrive_id:
        description: "Insert GDrive ID"
        required: false
        default: ""

jobs:
  downloads:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Environment
      run: |
        sudo apt update > /dev/null 2>&1
        sudo apt install -y python3 python3-pip > /dev/null 2>&1
        pip3 install gdown > /dev/null 2>&1
        mkdir -p downloads

    - name: Download From GDrive
      if: ${{ github.event.inputs.gdrive_id != '' }}
      run: |
        gdown https://drive.google.com/uc?id=${{ github.event.inputs.gdrive_id }} -O downloads/ > /dev/null

    - name: Download From Wget
      if: ${{ github.event.inputs.wget_link != '' }}
      run: |
        wget ${{ github.event.inputs.wget_link }} -O downloads/$(echo "${{ github.event.inputs.wget_link }}" | awk -F/ '{print $NF}') > /dev/null

    - name: Set up date
      id: set_date
      run: |
        export TZ='Asia/Jakarta'
        echo "date_time=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Create Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      with:
        name: Ajiputra-Wrt Rootfs
        tag_name: all
        draft: false
        prerelease: false
        files: |
              downloads/*
        body: |
              Kumpulan Rootfs
